### ISSUE TITLE
How do we get Stuff from the Micro:Bit sensors?

### ISSUE THREAD

**Issue by Simon-Ogorek** [DiamondChicken0/EggOS#1]
This seems like a fairly difficult challenge as there is no direct way to sync up the micro: bit with a desktop because it uses "MicroPython."

However, the micro: bit has persistent files, so we have to create a file with our data, have the connected computer read it, and generate another file to say that the transfer is done so it doesn't get overwritten mid-check.

Profit.

**Comment by Simon-Ogorek** [comment]
Documentation for micro: bit : https://microbit-micropython.readthedocs.io/en/v1.0.1/filesystem.html

**Comment by jkst9** [comment]
There is a python module called pyserial which we could use with the microbit sending serial data. I have to figure out how it works first though
